Netflix/aminator

- aminator/plugins/provisioner/aptitude.py
the dependency resolves for hold are crazy, install is more sane.  Both require a config file  `/etc/apt/apt.conf.d/00aptitude-sane-resolve.conf` with the contents:
```
Aptitude {
ProblemResolver {
SolutionCost "priority, removals, canceled-actions";
};
};
```
otherwise aptitude will find the "best" resolve strategy is to remove the package you want installed if it has any dependencies.
> change from aptitude hold to aptitude install

- aminator/plugins/blockdevice/base.py
- aminator/plugins/blockdevice/linux.py
- aminator/plugins/volume/linux.py
This pull adds a --partition parameter to the linux block device plugin to facilitate mounting of volumes with partition tables. It also adds in proper handling of partitioned volumes to the linux volume plugin. It's currently being used in deployment to create HVM AMI's with the ansible and yum provisioners.
This follows the general concept outlined by @mtripoli in issue https://github.com/Netflix/aminator/issues/59
Usage example:
```
aminate -e ec2_ansible_amzn -n my_ami_name --partition 1 --vm-type hvm -B my-ami-id my/playbook.yml --debug
```
> Add --partition parameter to allow mounting of partitioned volumes

- aminator/plugins/distro/linux.py
- aminator/plugins/metrics/logger.py
We will still abort and roll-back if there is an exception, but if the short-circuit file is missing, just warn about it.
Also fix a few cases of log.warn that should be log.warning
> just warn if short-circuit file is missing

- aminator/plugins/provisioner/aptitude.py
Aptitude likes to occasionally select solutions that involve downgrading the package requested. We can fix this more directly by tuning the ProblemResolver, but this provides a safeguard that fails the bake if aptitude does install the wrong package version in the end. It does NOT currently do any checking of dependencies installed, just the main requested package.
cc @coryb @kvick
> make aptitude provisioner verify correct version was installed

- aminator/plugins/provisioner/apt.py
- aminator/plugins/provisioner/aptitude.py
Some refactoring/cleanup here to try to avoid some repetition, but the main change is having the apt and aptitude provisioners, when doing a local install, delay apt-get update until after dpkg -i and before the deps are fixed. This hack allows one to package an apt sources file in their package and have the repositories used for dependencies during the dep fixing phase.
cc @coryb @kvick
> change deb local install to delay metadata refresh until after dpkg -i

- aminator/plugins/provisioner/apt.py
Dumb mistake in my last set of changes -- @classmethod and @staticmethod amongst others need to be the last decorators applied to methods since they turn things into descriptors.
> Decorator ordering bug

- aminator/plugins/provisioner/apt.py
- aminator/plugins/provisioner/aptitude.py
the metrics plugin expects to wrap instance methods and have access to instance state like <instance>._config. rather than chase all the cases down, simply revert for now
cc @coryb
> fix metrics plugin breakage due to instance methods becoming class methods

- aminator/config.py
- aminator/environment.py
- aminator/plugins/blockdevice/base.py
- aminator/plugins/blockdevice/linux.py
- aminator/plugins/blockdevice/null.py
- aminator/plugins/cloud/base.py
- aminator/plugins/cloud/ec2.py
- aminator/plugins/distro/base.py
- aminator/plugins/distro/linux.py
- aminator/plugins/finalizer/base.py
- aminator/plugins/finalizer/tagging_base.py
- aminator/plugins/finalizer/tagging_s3.py
- aminator/plugins/metrics/base.py
- aminator/plugins/provisioner/base.py
- aminator/plugins/volume/base.py
- aminator/plugins/volume/linux.py
- aminator/util/linux.py
We surface stack traces in the simple bakery log output which seems to overwhelm and confuse users. This changes usage of logging.exception to log.debug with exc_info set to True when encountered in a try/except and exc_info=(typ, val, trc) from the context manager when we exit a context manager due to an exception.
For generic context manager exits I simply shuffled the output to debug, but for regular try/catch exceptions, I paired the debug w/ stack trace with a warn, error, or critical log that will show up in the simple log output.
cc @coryb @kvick
> Move stack traces into detailed debug logs

- .gitignore
- GNUmakefile
- aminator/plugins/blockdevice/default_conf/aminator.plugins.blockdevice.linux.yml
- aminator/plugins/blockdevice/linux.py
- setup.cfg
This fixes #234 -- allows one to avoid use of minor devices (/dev/xvdg1 versus /dev/xvdg) for block device allocation as HVM instances in EC2 can only have EBS volumes attached to major devices.
cc @coryb @kvick
> fix #234 - block device minor device number configuration

- README.rst
- aminator/util/linux.py
- setup.cfg
Wrap Popen.stdout and .stderr with io.open (which will open in text mode) and encode the buffer as utf-8 before doing anything with it
(cc @coryb )
> better handling of multibyte unicode output

- aminator/plugins/cloud/ec2.py
boto.ec2.Volume.delete() simply returns True/False upon success/failure, but spews to ERROR if boto.ec2.Volume.update() is called against a non-existent volume (which ends up dropping an XML error that may confuse end users). Simply rely on Volume.delete() returning True/False and log (to DEBUG for now) if a volume deletion returns False
cc @coryb -- this should get rid of 
```
2016-08-11 04:28:24 - 400 Bad Request
2016-08-11 04:28:24 - <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidVolume.NotFound</Code><Message>The volume 'vol-xxxxxxxxx' does not exist.</Message></Error></Errors><RequestID>xxxxxxxxxx</RequestID></Response>
```
from output in the internal UI
> quiet down plugins.cloud.ec2.EC2CloudPlugin.delete_volume

- aminator/plugins/cloud/ec2.py
- requirements.txt
@bmoyles 
lets cache the base ami lookup since base changes infrequently and can be very slow to lookup
using dill due to recursive data structures within boto.ec2.image.Image objects.  json, yaml and pickle failed to serialize/deserialize correctly.
> cache base ami lookup

- aminator/__init__.py
- aminator/plugins/cloud/ec2.py
- aminator/plugins/finalizer/tagging_base.py
- requirements.txt
Per issue #249, refactor _register_image to use boto3 which supports setting the EnaSupport flag during AMI registration, when specified during the aminate call.
> Enable ENA support during AMI registration

- aminator/plugins/cloud/ec2.py
Per issue #252, check for `botoclient` `ClientError` during registration calls so that the retry logic is properly handled.
Fixed an improper check of error code at line 357 (needed to look at `ClientError.response`)
Finally, restored a log line that is useful by downstream workers.
> Automatic retry on duplicate AMI name via decorator fails due to improper exception handling

- aminator/__init__.py
- aminator/plugins/cloud/ec2.py
- aminator/plugins/finalizer/default_conf/aminator.plugins.finalizer.tagging_ebs.yml
- aminator/plugins/finalizer/default_conf/aminator.plugins.finalizer.tagging_s3.yml
- aminator/plugins/finalizer/tagging_base.py
So this _should_ wrap up #252 and #249 with fixes to some problems when doing instance-store registrations and providing correct parameters.  Surprisingly `architecture`, wasn't getting propagated correctly for instance store bakes (I kept thinking it should have been in `context.base_ami.architecture`), so decided to make it a default configuration and overridable via the finalizers per @bmoyles feedback.
The Caveat Emptor here is that this will now happily allow you to bake on `x86_64` and register it as `i386`
> Fix instance-store registration using boto3 and add architecture config and cli option

- aminator/util/linux.py
always call makedirs() on the mountpoint in case it does not exist
> always call makedirs() on the mountpoint

- aminator/plugins/cloud/ec2.py
During testing, received AttributeErrors during `allocate_base_volume`  Added config defaults.
`
File "../python/local/lib/python2.7/site-packages/aminator/plugins/cloud/ec2.py", line 187, in allocate_base_volume
volume_type = context.cloud.provisioner_ebs_type
File ".../python/local/lib/python2.7/site-packages/bunch/__init__.py", line 121, in __getattr__
raise AttributeError(k)
`
> add default config stuff.  this fixes the AttributeErrors

- aminator/plugins/base.py
- aminator/plugins/cloud/default_conf/aminator.plugins.cloud.ec2.yml
- aminator/plugins/cloud/ec2.py
- aminator/plugins/finalizer/default_conf/aminator.plugins.finalizer.tagging_s3.yml
- aminator/plugins/finalizer/tagging_s3.py
- aminator/plugins/volume/default_conf/aminator.plugins.volume.linux.yml
- aminator/plugins/volume/linux.py
- aminator/util/linux.py
Allows for specification of a root volume size as well as optional resize2fs which should (once the API is wired up) allow for specification of root volume sizes that exceed that of the base.
> Bmoyles allow root volume size

- aminator/plugins/cloud/default_conf/aminator.plugins.cloud.ec2.yml
- aminator/plugins/cloud/ec2.py
default should be to not specify a fixed root volume size (but allow for that configuration), and when that volume size is not provided, inherit the size from the base AMI
> adjust default root volume size behavior

- aminator/util/linux.py
From `e2fsck(8)`
```
EXIT CODE
The exit code returned by e2fsck is the sum of the following conditions:
0    - No errors
1    - File system errors corrected
2    - File system errors corrected, system should
be rebooted
4    - File system errors left uncorrected
8    - Operational error
16   - Usage or syntax error
32   - E2fsck canceled by user request
128  - Shared library error
```
I could be convinced to allow 2 as well, but given our patterns, suspect that's an unlikely result
> an e2fsck return code of 1 should not be a failure

- aminator/plugins/cloud/ec2.py
Needed to change the way the parameters were passed to `_register_image` as the `registration_retry` decorator is expecting `kwargs` and not a dict of values.
> Retry for duplicate AMI name fails during register_ami

- aminator/plugins/volume/linux.py
- aminator/util/linux.py
when root volume size support was added, partitioned volumes were not considered. this adds a growpart function for calling growpart against the partition prior to a resize2fs and ensures that fsck, resize2fs, and friends are all called against the partition, not the full block device
> partition-aware resize support

- aminator/exceptions.py
- aminator/plugins/distro/linux.py
- aminator/plugins/volume/linux.py
- aminator/util/linux.py
Inside umount, inspect the result and raise a new CommandException to trigger a retry. If we exhaust retries, the CommandException is still raised, so catch that in the caller and handle appropriately.
Could probably do without the else: clauses in the try/except as a run w/o an exception should return a result where result.success == True, but kept it in as a sanity check/safeguard.
> do some juggling to wrap the unmount call in a retry

- aminator/environment.py
- aminator/exceptions.py
- aminator/plugins/distro/base.py
- aminator/plugins/distro/debian.py
- aminator/plugins/distro/default_conf/aminator.plugins.distro.debian.yml
- aminator/plugins/distro/default_conf/aminator.plugins.distro.redhat.yml
- aminator/plugins/distro/linux.py
- aminator/plugins/provisioner/base.py
- aminator/plugins/volume/linux.py
- aminator/util/linux.py
- tests/TestAptProvisionerPlugin.py
This consolidates mounting/unmounting in the chroot components in the distro plugins rather than have some handled by the volume plugin and some handled by the distro plugin.
In addition, it adds support for configurable use of `umount --recursive`, tries to unmount things if something goes wrong during chroot setup, and provides a cleaner view of open files in `busy_mount` when looking for open files against a bind mount that may have open handles outside the chroot.
> recursive unmount support + better mount/unmount handling
